[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

lib_deps = 
    zinggjm/GxEPD2
    h2zero/NimBLE-Arduino

